version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: nobilis_postgres
    restart: always
    environment:
      POSTGRES_DB: nobilis_mes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - nobilis_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nobilis_mes"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nobilis_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres123
      DATABASE_NAME: nobilis_mes
      JWT_SECRET: your-super-secret-jwt-key
      CORS_ORIGIN: http://77.233.212.181:8080
      PORT: 3001
      API_PREFIX: api
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - nobilis_network

volumes:
  postgres_data:
    driver: local

networks:
  nobilis_network:
    driver: bridge